name: freva-web
channels:
  - conda-forge
dependencies:
  - bleach
  - django-ipware
  - django-webpack-loader
  - djangorestframework
  - fabric
  - freva
  - git
  - gunicorn
  - mysql-client <9
  - mysqlclient
  - paramiko
  - pip
  - pygtail
  - redis-py
  - toml
  - pip:
      - django-datatable-view
      - django-templated-email
      - django_compressor
      - django-bootstrap-v5
      - django-model-utils
      - djproxy
